
# Rename long Google Forms questions into shorter variable names
rename_map = {
    "Timestamp": "timestamp",
    "If you are willing to be contacted for a follow-up study or possible interview, please leave your email address below.\nThis is optional and will only be used in relation to this research project.": "contact_email",
    "Please indicate your age": "age_group",
    "What is the 4-digit postcode of your home address?": "postcode4",
    "How long have you lived in the neighbourhood you currently reside in?": "residence_length",
    "What is your main daily status?": "daily_status",
    "What is your main mode of transport for everyday trips in this area?": "main_mode",
    "How easy is it for you to reach places you use regularly in your daily life from this neighbourhood?": "daily_place_access",
    "How fixed is your daily schedule on most days?": "schedule_fixedness",
    "On a typical day, how much free time do you usually have between finishing your main daily activity and settling at home?": "free_time_after_activity",
    "When you have some free time during or after your daily routine, what do you usually do?": "free_time_activity",
    "Has easier and faster transportation changed where you usually spend time between home, work, school, or other activities?": "transport_changed_timeplace",
    "How easy is it for you to reach places where you might casually spend time, such as cafés, parks, libraries, barbershops, or community spaces?": "casual_place_access",
    "During your day, how often do you pass places where you could easily stop for a bit?": "pass_stop_places_freq",
    "How easy is it for you to stop somewhere for a while on your way home, just because you feel like it?": "spontaneous_stop_ease",
    "If a café, park, or potential third place was a 5-minute detour from your usual route, how likely would you be to stop?": "five_min_detour_likely",
    "How many minutes out of your way would you be willing to go to stop somewhere casually?": "detour_tolerance_mins",
    "What most limits your ability to stop and spend time in local places? ": "main_stop_barrier",
    "Do any of the following make it harder for you to use local places regularly?": "regular_use_barriers",
    "How often do you visit a local third place in this neighbourhood?": "third_place_visit_freq",
    "When you visit these places, is it usually…": "visit_planning_type",
    "How often do you stay longer than originally intended when visiting a local place in your neighbourhood?": "linger_freq",
    "What kinds of places do you use most often for casual time in your neighbourhood?": "place_type_used",
    "What is the main reason you use these places?": "main_place_reason",
    "When you do visit a local place, how often do you return to the same place within the same week?": "same_place_return_freq",
    "Do you have a local place you visit so regularly that staff or other visitors would recognize you?": "recognized_regular",
    "How often do you see familiar faces in local public or semi-public places in your neighbourhood, even if you do not know them personally?": "familiar_faces_freq",
    "How often do you have small interactions with people you recognize in the neighbourhood, such as greeting, nodding, or short conversation?": "small_interactions_freq",
    "I feel at ease in local public places in my neighbourhood.": "ease_public_places",
    "When you spend time in local places, do you tend to be alone, with people you already know, or do you sometimes interact with people you do not know?": "social_use_type",
    "I feel a sense of belonging in this neighbourhood.": "belonging",
    "Being in local places in this neighbourhood makes the area feel more familiar to me.": "place_familiarity",
    "I feel comfortable spending time in local places here without needing a specific purpose.": "comfort_no_purpose",
    "My daily routine leaves me enough unstructured time to stop somewhere locally.": "unstructured_time",
    "Even when places are accessible, I usually feel too rushed to spend time there.": "too_rushed",
    "Improved transport or faster travel in my daily life has made it easier for me to spend time in local places.": "transport_enables_local_time",
    "Improved transport or faster travel in my daily life has made me more likely to go directly home or elsewhere instead of lingering locally.": "transport_encourages_direct_travel",
    "Can you describe a place in this neighbourhood where you feel comfortable spending time? What makes it feel that way?": "comfortable_place_text",
    "Can you describe anything that makes it harder for you to stop, linger, or return regularly to local places in this neighbourhood?": "barriers_text",
    "Do you think transport and daily routines in this area support or undermine casual social life? Please explain briefly.": "transport_routines_social_life_text",
    "Imagine your commute or daily travel became significantly faster. How do you think that would change how you spend time in your neighbourhood?": "faster_travel_effect_text",
    "Can you describe how you first started regularly visiting a local place in your neighbourhood? Was it gradual, accidental, or deliberate?": "regular_visit_origin_text",
}

